[project.vvfrontend]

branch = "master"
secret = "xxx"
cwd = 'c:\games'
steps = [
    ["goprint.exe","start"],
    ["gosleep.exe","2"],
    ["goprint.exe","mid"],
    ["gosleep.exe","3"],
    ["goprint.exe","end"]
]
stepTimeout = 600