[project.vvfrontend]

branch = "master"
secret = "xxx"
cwd = '/home/neelu/experiments'
steps = [
    ["echo","start"],
    ["sleep","2"],
    ["git","--help"],
    ["sleep","2"],
    ["sleep","1"],
    ["sleep","1"],
    
]
stepTimeout = 600