[project.vvfrontend]

branch = "master"
secret = "xxx"
cwd = 'c:\games'
steps = [
    ["goprint","start"],
    ["gosleep","2"],
    ["goprint","mid"],
    ["gosleep","5"],
    ["goprint","end"],
    ["gosleep","1"],
    ["gosleep","1"],
    ["gosleep","1"],
    ["gosleep","1"],
    ["gosleep","1"],
]
stepTimeout = 600