[project.vvfrontend]

branch = "master"
secret = "xxx"
cwd = '/home/neelu/work'
steps = [
    ["echo","start"],
    ["sleep","2"],
    ["echo","mid"],
    ["sleep","3"],
    ["echo","end"]
]
stepTimeout = 600