[project.vvfrontend]

branch = "master"
secret = "xxx"
cwd = '/home/neelu/experiments'
steps = [
    ["echo","start"],
    ["sleep","2"],
    ["echo","mid"],
    ["sleep","2"],
    ["echo","end"],
    ["sleep","1"],
    ["sleep","1"],
    ["sleep","1"],
    ["sleep","1"],
    ["sleep","1"],
]
stepTimeout = 600